#config/routes.yaml

homepage:
  path: /
  controller: App\Controller\AppController::index

article_add:
  path: /add
  controller: App\Controller\AppController::add

article_show:
  path: /show/{url}
  controller: App\Controller\AppController::show

article_edit:
  path: /edit/{id}
  controller: App\Controller\AppController::edit
  requirements:
    id: '\d+'

article_remove:
  path: /remove/{id}
  controller: App\Controller\AppController::remove
  requirements:
    id: '\d+'

logout:
    path: /logout